server {
    listen 5173;

    root /usr/share/nginx/html;
    index index.html;

    location /uploads/ {
        proxy_pass http://server:5000/uploads/;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
